import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cesc_core/cesc_core.dart';
import 'package:net_core/net_core.dart';
import 'package:pow_core/pow_core.dart';
import 'package:utxo_core/utxo_core.dart';

/// Builds lib/src/checkpoint.g.dart from the live network (release
/// tooling). Usage: `dart run tool/gen_checkpoint.dart START_HEIGHT START_HASH [HOST:PORT]`
/// The start block must be at least 5041 + 600 blocks below the tip.
Future<void> main(List<String> args) async {
  final p = Cryptoescudo.params;
  final startHeight = int.parse(args[0]);
  final (host, port) = splitHostPort(args.length > 2 ? args[2] : p.fixedPeers.first, p.port);
  final peer = await Peer.connect(IoTransport(), p, host, port, startHeight: 0);
  stderr.writeln('connected to $peer');
  final headers = <BlockHeader>[];
  var last = hashFromHex(args[1]);
  final pow = p.pow();
  while (true) {
    final reply = await peer.request('getheaders', Msg.getHeaders(p.protocolVersion, [last]), (m) => m.command == 'headers');
    final batch = Msg.parseHeaders(reply.payload);
    if (batch.isEmpty) break;
    for (final h in batch) {
      if (!bytesEqual(h.prevHash, last)) throw StateError('chain break');
      if (!CompactTarget.meets(pow.hash(h.serialize()), CompactTarget.decode(h.bits))) throw StateError('bad pow');
      last = h.hash;
      headers.add(h);
    }
    stderr.writeln('${headers.length} headers, up to ${startHeight + headers.length}');
    if (batch.length < 2000) break;
  }
  await peer.close();
  final tip = startHeight + headers.length;
  final cpHeight = tip - 600;
  final window = p.retarget.window;
  if (cpHeight - window + 1 <= startHeight) throw StateError('start further back');
  // Heights startHeight+1+i are headers[i].
  BlockHeader at(int h) => headers[h - startHeight - 1];
  final hist = ByteData(window * 8);
  for (var i = 0; i < window; i++) {
    final h = at(cpHeight - window + 1 + i);
    hist.setUint32(i * 8, h.bits, Endian.little);
    hist.setUint32(i * 8 + 4, h.time, Endian.little);
  }
  final cp = at(cpHeight);
  File('lib/src/checkpoint.g.dart').writeAsStringSync('''// Generated by tool/gen_checkpoint.dart from the live network on
// ${DateTime.now().toUtc().toIso8601String().substring(0, 10)}; do not edit.
// Block $cpHeight and the nBits and time of the $window blocks up to it.

const int checkpointHeight = $cpHeight;
const String checkpointHash = '${cp.id}';
const String checkpointHistory =
    '${base64.encode(hist.buffer.asUint8List())}';
''');
  Directory('test/fixtures').createSync(recursive: true);
  final after = BytesBuilder();
  for (var h = cpHeight + 1; h <= tip; h++) {
    after.add(at(h).serialize());
  }
  File('test/fixtures/headers_after_checkpoint.bin').writeAsBytesSync(after.takeBytes());
  stdout.writeln('checkpoint $cpHeight ${cp.id}; ${tip - cpHeight} headers after it saved as a fixture');
}
