import 'dart:convert';
import 'dart:io';

/// Release tooling (not runtime): writes lib/src/monero/checkpoint.g.dart with
/// the last [difficultyBlocksCount] block headers (id, timestamp, cumulative
/// difficulty) at a height a few days old, read from a Monero node's JSON-RPC.
///
/// At runtime the light peer syncs forward from this point, computes every
/// later difficulty itself and cross-checks the resulting cumulative
/// difficulty against several P2P peers, so a wrong checkpoint is detected.
///
///   dart run tool/gen_checkpoint.dart https://node:18081 [depth]
Future<void> main(List<String> args) async {
  final url = Uri.parse('${args.isNotEmpty ? args[0] : 'https://xmr-node.cakewallet.com:18081'}/json_rpc');
  final depth = args.length > 1 ? int.parse(args[1]) : 3000; // blocks behind the tip (~4 days)
  const count = 735;
  final client = HttpClient()..connectionTimeout = const Duration(seconds: 20);

  Future<Map<String, Object?>> rpc(String method, Map<String, Object?> params) async {
    final req = await client.postUrl(url);
    final payload = utf8.encode(jsonEncode({'jsonrpc': '2.0', 'id': '0', 'method': method, 'params': params}));
    req.headers.contentType = ContentType('application', 'json');
    req.contentLength = payload.length; // monerod rejects chunked bodies
    req.add(payload);
    final resp = await req.close();
    final body = await resp.transform(utf8.decoder).join();
    final m = jsonDecode(body) as Map<String, Object?>;
    if (m['error'] != null) throw StateError('$method: ${m['error']}');
    return m['result']! as Map<String, Object?>;
  }

  final info = await rpc('get_last_block_header', {});
  final tipHeight = ((info['block_header']! as Map<String, Object?>)['height']! as num).toInt();
  final end = tipHeight - depth;
  final start = end - count + 1;
  final headers = <Map<String, Object?>>[];
  for (var s = start; s <= end; s += 500) {
    final e = (s + 499) > end ? end : s + 499;
    final r = await rpc('get_block_headers_range', {'start_height': s, 'end_height': e});
    headers.addAll((r['headers']! as List).cast<Map<String, Object?>>());
  }
  client.close();
  if (headers.length != count) throw StateError('got ${headers.length} headers');

  final sb = StringBuffer()
    ..writeln('// GENERATED by tool/gen_checkpoint.dart from ${url.host}; do not edit.')
    ..writeln('// Monero mainnet headers $start..$end (tip was $tipHeight).')
    ..writeln()
    ..writeln('const int checkpointEndHeight = $end;')
    ..writeln()
    ..writeln('/// (id, timestamp, cumulative difficulty) for heights '
        '[checkpointEndHeight - ${count - 1}, checkpointEndHeight].')
    ..writeln('const List<(String, int, String)> checkpointHeaders = [');
  for (final h in headers) {
    final cdHex = (h['wide_cumulative_difficulty'] as String?) ??
        '0x${((h['cumulative_difficulty_top64'] as num? ?? 0).toInt() << 64 | (h['cumulative_difficulty']! as num).toInt()).toRadixString(16)}';
    final cd = BigInt.parse(cdHex.startsWith('0x') ? cdHex.substring(2) : cdHex, radix: 16);
    sb.writeln("  ('${h['hash']}', ${h['timestamp']}, '$cd'),");
  }
  sb.writeln('];');
  final out = File('lib/src/monero/checkpoint.g.dart');
  out.writeAsStringSync(sb.toString());
  stdout.writeln('wrote ${out.path}: heights $start..$end');
}
